name: Testes Regressivos de API

on: 
  push:
    branches:
      - main
      
jobs:
  run-api-tests: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        
      - name: Instalando dependências
        run: npm install
        
      - name: Executando testes - dev
        run: npm run test:dev
